# Generated by Django 2.1.3 on 2018-11-16 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=200)),
                ('_calroie', models.CharField(max_length=200)),
                ('_text', models.TextField()),
                ('_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2018, 11, 16, 8, 52, 9, 1900, tzinfo=utc))),
            ],
        ),
    ]
